global:
  registry: docker.io/daprio
  tag: '1.10.2'
  dnsSuffix: ".cluster.local"
  logAsJson: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ""
  nodeSelector: {}
  tolerations: []
  rbac:
    namespaced: false
  ha:
    enabled: false
    replicaCount: 3
    disruption:
      minimumAvailable: ""
      maximumUnavailable: "25%"
  prometheus:
    enabled: true
    port: 9090
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m
  daprControlPlaneOs: linux
  labels: {}
  k8sLabels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Values.global.tag }}"
    app.kubernetes.io/part-of: "dapr"
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/component: "{{ .Values.component }}" # Should be set in each subchart

  issuerFilenames: {}
  ## the issuerFilenames dictionary, if setup, have to contain 3 keys: ca,cert,key
  # issuerFilenames:
  #   ca: "ca.crt"
  #   cert: "tls.crt"
  #   key: "tls.key"

dapr_operator:
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1000m

dapr_sidecar_injector:
  resources:
    requests:
      memory: 30Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1000m

dapr_sentry:
  resources:
    requests:
      memory: 30Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1000m

dapr_dashboard:
  enabled: false

dapr_placement:
  cluster:
    forceInMemoryLog: true
  runAsNonRoot: true